name: Trigger auto deployment for hackernews

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hackernews-AutoDeployTrigger-63667686-ca23-49f2-9e16-bb88f99a315b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HACKERNEWS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hackernews1si21cs009.azurecr.io
          registryUsername: ${{ secrets.HACKERNEWS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HACKERNEWS_REGISTRY_PASSWORD }}
          containerAppName: hackernews
          resourceGroup: Hackernews
          imageToBuild: hackernews1si21cs009.azurecr.io/hackernews:${{ github.sha }}
          
            

     

